let interests = [
    "Blogging",
    "Bullet Journaling",
    "Charity Work",
    "Coaching",
    "Community Service",
    "Event Hosting",
    "Fundraising",
    "Mentoring",
    "Party Planning",
    "Podcasting",
    "Public Speaking",
    "Tutoring",
    "Vlogging",
    "Volunteering",
    "Public Relations",
    "3D Printing",
    "Animation", 
    "Cartooning",
    "Coding",
    "Computer Games",
    "Computer Programming",
    "Content Marketing",
    "Digital Art",
    "DJing", 
    "Domain Research",
    "E-Commerce Development",
    "Editing and Proofreading",
    "Email Marketing",
    "Encoding",
    "Filmmaking",
    "Game Design",
    "Gaming",
    "Graphic Designing",
    "Logo Design",
    "Lyric & Music Videos",
    "Making e-cards",
    "Music Promotion",
    "Online Marketing", 
    "Photo Manipulation",
    "Photoshop",
    "Podcasting",
    "SEO",
    "Social Media Marketing",
    "Stop Motion Animation",
    "Video Editing",
    "Video Games",
    "Video Production",
    "Videogame Developing",
    "Videography",
    "Visual Effects",
    "Voice Over",
    "Web Analytics",
    "Web and Mobile Design",
    "Web Design",
    "Web Development",
    "Web Traffic",
    "Website Optimization",
    "Youtubing",
    "Audiobook Production",
    "Beatboxing",
    "Composing",
    "Instrument Playing",
    "Jingles & Intros",
    "Karaoke",
    "Mixing & Mastering",
    "Music Transcription",
    "Music Writing",
    "Rapping",
    "Singing",
    "Song Writing",
    "Sound Effects",
    "Vocal Tuning",
    "Airsoft",
    "American Football", 
    "Archery", 
    "Australian Football", 
    "Badminton", 
    "Baseball", 
    "Basketball", 
    "Baton Twirling", 
    "Beach Volleyball",
    "Bicycling",
    "Billiards",
    "Bodybuilding",
    "Bowling",
    "Boxing", 
    "Cheerleading",
    "Chess", 
    "Color Guard",
    "Competitive E-Sports", 
    "Cooking Competitions",
    "Cricket",
    "Curling",
    "Cycling",
    "Darts",
    "Disc Golf",
    "Dodgeball",
    "Dog Sports",
    "Falconry",
    "Fencing",
    "Field hockey",
    "Figure skating",
    "Fish Tournaments",
    "Flag Football",
    "Floorball",
    "Football", 
    "Golf",
    "Golfing",
    "Handball",
    "Hockey",
    "Horseback riding", 
    "Hot Air Ballooning",
    "Ice Hockey",
    "Juggling", 
    "Lacrosse",
    "Marksmanship",
    "Paintball",
    "Racquetball",
    "Roller Derby",
    "Roller Skating",
    "Rugby",
    "Sailing",
    "Skateboarding",
    "Skeet Shooting",
    "Skiing",
    "Snowboarding",
    "Soccer",
    "Speed skating",
    "Surfing",
    "Swimming",
    "Table Tennis",
    "Tennis",
    "Volleyball",
    "Wrestling",
    'Architecture', 
    'Balloon Art' ,
    'Balloon Twisting',
    'Beadwork and Beading', 
    'Blacksmithing', 
    'Body Art',
    'Book Making',
    'Calligraphy', 
    'Candle Making', 
    'Ceramics-Pottery',
    'Clothesmaking', 
    'Collage Making', 
    'Collecting', 
    'Comic Book Art', 
    'Cooking', 
    'Cosmetics',
    'Cosplaying', 
    'Crochet', 
    'Cross Stitching', 
    'Decorating', 
    'DIY Activities',
    'Doll Making',
    'Doodling', 
    'Drawing', 
    'Embroidery', 
    'Engraving', 
    'Fashion', 
    'Fashion Design', 
    'Felting',
    'Fiber Art', 
    'Floristry', 
    'Flower Arranging', 
    'Furniture Restoration', 
    'Gardening', 
    'Glass Blowing', 
    'Graffiti', 
    'Gun Smithing', 
    'Handicraft',
    'Handprinting', 
    'Ice Sculpture',
    'Illustration', 
    'Interior Design', 
    'Jewelry Making', 
    'Knitting', 
    'Knotting', 
    'Lace Making', 
    'Leather Crafting', 
    'Leatherwork', 
    'Lomography', 
    'Magic', 
    'Nail Art', 
    'Origami', 
    'Painting and Drawing', 
    'Papier-Mache',
    'Photography', 
    'Pottery',
    'Puppetry', 
    'Pyrography',
    'Quilling', 
    'Restoring Antiques',
    'Rock Balancing', 
    'Rubber Stamping', 
    'Sand Art', 
    'Scrapbooking', 
    'Screen Printing',
    'Sculpting', 
    'Sewing', 
    'Shoemaking', 
    'Silk Screening', 
    'Sketching', 
    'Soap Making',
    'Tattooing', 
    'Watercolor Painting', 
    'Weaving',
    "Welding", 
    "Wire Jewelry Making", 
    "Wood Carving",
    'Breadmaking',
    'Brewing',
    'Cake Decorating', 
    'Card games', 
    'Chess',
    'Cooking', 
    'Exercising', 
    'Home Brewing',
    'Jigsaw Puzzles',
    'Meditation', 
    'Pilates',
    'Speed Cubing',
    'Tai Chi', 
    'Weightlifting', 
    'Yoga', 
    'Zumba',
    'Backpacking', 
    'Biking', 
    'Bird Watching', 
    'Camping', 
    'Canoeing', 
    'Climbing', 
    'Cycling', 
    'Farming',
    'Fishing', 
    'Hiking', 
    'Hunting', 
    'Jogging', 
    'Karate',
    'Landscaping', 
    'Racing',
    'Rock Climbing', 
    'Sailing', 
    'Shooting', 
    'Skateboarding', 
    'Skating',
    'Skiing',
    'Speed Walking', 
    'Spelunking',
    'Swimming', 
    'Travelling', 
    'Trekking',
    'Astrology' ,
    'Astronomy',
    'Chemistry',
    'Electronics',
    'Meteorology', 
    'Microscopy',
    'Model airplanes',
    'Model Rocketry',
    'Telescope Making',
    'Acting' ,
    'Childcare',
    'Dancing',
    'Debate',
    'Dog Sitting', 
    'Impersonation', 
    'Language Learning', 
    'Modeling',
    'Reading', 
    'Resume Writing',
    'Speechwriting',
    'Story-Writing', 
    'Translation',
    'Creative Writing',
    'Reading Books',
    'Collecting Books',
    'Writing Poetry',
    'Lifestyle Blogging',
    'Food Blogging',
    'Travel Blogging',
    'Baking',
    'Vegan Cooking',
    'Writing Recipes',
    'Food Styling',
    "Karate",
    'Making Furniture'  
]

export default interests