export const interests = {
    social: [
        "Blogging",
        "Bullet Journaling",
        "Charity Work",
        "Coaching",
        "Community Service",
        "Event Hosting",
        "Fundraising",
        "Mentoring",
        "Party Planning",
        "Podcasting",
        "Public Speaking",
        "Tutoring",
        "Vlogging",
        "Volunteering",
        "Public Relations"
    ],
    tech: [
        "3D Printing",
        "Animation",
        "Cartooning",
        "Coding",
        "Computer Games",
        "Computer Programming",
        "Content Marketing",
        "Digital Art",
        "DJing",
        "Domain Research",
        "E-Commerce Development",
        "Editing and Proofreading",
        "Email Marketing",
        "Encoding",
        "Filmmaking",
        "Game Design",
        "Gaming",
        "Graphic Designing",
        "Logo Design",
        "Lyric & Music Videos",
        "Making e-cards",
        "Music Promotion",
        "Online Marketing",
        "Photo Manipulation",
        "Photoshop",
        "Podcasting",
        "SEO",
        "Social Media Marketing",
        "Stop Motion Animation",
        "Video Editing",
        "Video Games",
        "Video Production",
        "Videogame Developing",
        "Videography",
        "Visual Effects",
        "Voice Over",
        "Web Analytics",
        "Web and Mobile Design",
        "Web Design",
        "Web Development",
        "Web Traffic",
        "Website Optimization",
        "Youtubing"
    ],
    music: [
        "Audiobook Production",
        "Beatboxing",
        "Composing",
        "Instrument Playing",
        "Jingles & Intros",
        "Karaoke",
        "Mixing & Mastering",
        "Music Transcription",
        "Music Writing",
        "Rapping",
        "Singing",
        "Song Writing",
        "Sound Effects",
        "Vocal Tuning",
    ],
    sports: [
        "Airsoft",
        "American Football",
        "Archery",
        "Australian Football",
        "Badminton",
        "Baseball",
        "Basketball",
        "Baton Twirling",
        "Beach Volleyball",
        "Bicycling",
        "Billiards",
        "Bodybuilding",
        "Bowling",
        "Boxing",
        "Cheerleading",
        "Chess",
        "Color Guard",
        "Competitive E-Sports",
        "Cooking Competitions",
        "Cricket",
        "Curling",
        "Cycling",
        "Darts",
        "Disc Golf",
        "Dodgeball",
        "Dog Sports",
        "Falconry",
        "Fencing",
        "Field hockey",
        "Figure skating",
        "Fish Tournaments",
        "Flag Football",
        "Floorball",
        "Football",
        "Golf",
        "Golfing",
        "Handball",
        "Hockey",
        "Horseback riding",
        "Hot Air Ballooning",
        "Ice Hockey",
        "Juggling",
        "Lacrosse",
        "Marksmanship",
        "Paintball",
        "Racquetball",
        "Roller Derby",
        "Roller Skating",
        "Rugby",
        "Sailing",
        "Skateboarding",
        "Skeet Shooting",
        "Skiing",
        "Snowboarding",
        "Soccer",
        "Speed skating",
        "Surfing",
        "Swimming",
        "Table Tennis",
        "Tennis",
        "Volleyball",
        "Wrestling",
    ],
    arts: [
        'Architecture',
        'Balloon Art',
        'Balloon Twisting',
        'Beadwork and Beading',
        'Blacksmithing',
        'Body Art',
        'Book Making',
        'Calligraphy',
        'Candle Making',
        'Ceramics-Pottery',
        'Clothesmaking',
        'Collage Making',
        'Collecting',
        'Comic Book Art',
        'Cooking',
        'Cosmetics',
        'Cosplaying',
        'Crochet',
        'Cross Stitching',
        'Decorating',
        'DIY Activities',
        'Doll Making',
        'Doodling',
        'Drawing',
        'Embroidery',
        'Engraving',
        'Fashion',
        'Fashion Design',
        'Felting',
        'Fiber Art',
        'Floristry',
        'Flower Arranging',
        'Furniture Restoration',
        'Gardening',
        'Glass Blowing',
        'Graffiti',
        'Gun Smithing',
        'Handicraft',
        'Handprinting',
        'Ice Sculpture',
        'Illustration',
        'Interior Design',
        'Jewelry Making',
        'Knitting',
        'Knotting',
        'Lace Making',
        'Leather Crafting',
        'Leatherwork',
        'Lomography',
        'Magic',
        'Nail Art',
        'Origami',
        'Painting and Drawing',
        'Papier-Mache',
        'Photography',
        'Pottery',
        'Puppetry',
        'Pyrography',
        'Quilling',
        'Restoring Antiques',
        'Rock Balancing',
        'Rubber Stamping',
        'Sand Art',
        'Scrapbooking',
        'Screen Printing',
        'Sculpting',
        'Sewing',
        'Shoemaking',
        'Silk Screening',
        'Sketching',
        'Soap Making',
        'Tattooing',
        'Watercolor Painting',
        'Weaving',
        "Welding",
        "Wire Jewelry Making",
        "Wood Carving",
    ],
    indoor: [
        'Breadmaking',
        'Brewing',
        'Cake Decorating',
        'Card games',
        'Chess',
        'Cooking',
        'Exercising',
        'Home Brewing',
        'Jigsaw Puzzles',
        'Meditation',
        'Pilates',
        'Speed Cubing',
        'Tai Chi',
        'Weightlifting',
        'Yoga',
        'Zumba',
    ],
    outdoor: [
        'Backpacking',
        'Biking',
        'Bird Watching',
        'Camping',
        'Canoeing',
        'Climbing',
        'Cycling',
        'Farming',
        'Fishing',
        'Hiking',
        'Hunting',
        'Jogging',
        'Karate',
        'Landscaping',
        'Racing',
        'Rock Climbing',
        'Sailing',
        'Shooting',
        'Skateboarding',
        'Skating',
        'Skiing',
        'Speed Walking',
        'Spelunking',
        'Swimming',
        'Travelling',
        'Trekking'
    ],
    science: [
        'Astrology',
        'Astronomy',
        'Chemistry',
        'Electronics',
        'Meteorology',
        'Microscopy',
        'Model airplanes',
        'Model Rocketry',
        'Telescope Making'
    ],
    personal: [
        'Acting',
        'Childcare',
        'Dancing',
        'Debate',
        'Dog Sitting',
        'Impersonation',
        'Language Learning',
        'Modeling',
        'Reading',
        'Resume Writing',
        'Speechwriting',
        'Story-Writing',
        'Translation'
    ],
    literature: [
        'Creative Writing',
        'Reading Books',
        'Collecting Books',
        'Writing Poetry',
        'Lifestyle Blogging',
        'Food Blogging',
        'Travel Blogging'
    ],
    food: [
        'Baking',
        'Vegan Cooking',
        'Writing Recipes',
        'Food Styling',
    ],
    martial: [
        'Karate',
        'Judo',
        'Tai Chi',
        'Taekwondo',
        'Jiu Jitsu',
    ],
    film: [
        'Photography',
        'Videography',
        'Filmmaking',
        'Acting',
        'Drama',
        'Role Playing',
        'Theater'
    ],
    building: [
        'Making Furniture',
        'Autocad'
    ]
}

export const skills = {
    development: [
        'STEM Skills',
        'CAD',
        'Design',
        'Prototyping',
        'Testing',
        'Troubleshooting',
        'Project Launch',
        'Lean Manufacturing',
        'Workflow Development',
        'SolidWorks',
        'Magento',
        'WooCommerce',

        //develoepr skills
        "JavaScript", "HTML/CSS", "SQL", "Python", "Java", "Bash/Shell/PowerShell", "C#", "PHP", "C++", "TypeScript", "C", "Ruby", "Go", "Assembly", "Swift", "Kotlin", "R", "VBA", "Objective-C", "Scala", "Rust", "Dart", "Elixir", "Clojure", "WebAssembly", "jQuery", "React.js", "Angular/Angular.js", "ASP.NET", "Express", "Spring", "Vue.js", "Django", "Flask", "Laravel", "Ruby on Rails", "Drupal", "Node.js", ".NET", ".NET Core", "Pandas", "Unity 3D%", "React Native", "TensorFlow", "Ansible", "Cordova", "Xamarin", "Apache Spark", "Hadoop", "Unreal Engine", "Flutter", "Torch/PyTorch", "Puppet", "Chef", "CryEngine", "MySQL", "PostgreSQL", "Microsoft SQL Server", "SQLite", "MongoDB", "Redis", "MariaDB", "Oracle", "Elasticsearch", "Firebase", "DynamoDB", "Cassandra", "Couchbase", "Linux", "Windows", "Docker", "Android", "AWS", "MacOS", "Slack", "Raspberry Pi", "WordPress", "iOS", "Google Cloud Platform", "Microsoft Azure", "Arduino", "Heroku", "Kubernetes", "IBM Cloud or Watson"
    ],
    design: [
        'Photoshop',
        'Illustrator',
        'InDesign',
        'Figma',
        'InVision',
        'Sketch',
        'Adobe XD',
        'Adobe Creative Suite',
        'HTML',
        'UI/UX',
        'Typography',
        'Print Design',
        'CSS',
        'Bootstrap',
        'Web Design',
        'Branding',
        'Portfolio Management',
        'Digital Design Software',
        'Adobe Acrobat',
        'Adobe Flash',
        'Dreamweaver',
        'Quark',
        'QuarkXpress',
        'Photo Editing',
        'Choosing Fonts',
        'Logo Creation',
        'Layout',
        'Modifying Designs',
        'Spacing',
        'Storyboard Creation',
        'Color Sense',
        'Color Theory',
        'Composition',
        'Creating Models for Three-dimensional Forms',
        'Infographics',
        'Digital Printing',
        'Estimating Costs',
        'Integrating Visual Messages within Social Media Platforms',
        'Ad Design',
        'Color Schemes',
        'iWork Keynote',
        'Photography',
        'DSLR Cameras',
        'Production',
        'Targeting Visual Communications to Demographic Groups',
        'SEO/SEM',
        'PPC',
        'CRO',
        'A/B Testing',
        'Social Media Marketing and Paid Social Media Advertising',
        'Sales Funnel Management',
        'CMS Tools',
        'Graphic Design',
        'Motion Design',
        'Email Marketing',
        'Email Automation',
        'Data Visualization',
    ],
    leadership: [
        'Advising',
        'Coaching',
        'Conflict resolution',
        'Decision making',
        'Delegating',
        'Diplomacy',
        'Interviewing',
        'Motivation',
        'People management',
        'Problem solving',
        'Strategic thinking',
        'Management',
        'Motivational negotiation',
        'Strategic planning',
        'Delegation',
        'Entrepreneurial',
        'Agile',
        'Managing Cross-Functional Teams',
        'Scrum',
        'Performance Tracking',
        'Financial Modelling',
        'Ideation Leadership',
        'Feature Definition',
        'Forecasting',
        'Profit and Loss',
        'Scope Management',
        'Project Lifecycle Management',
        'Meeting Facilitation',
    ],
    professionalism: [
        'Dedication',
        'Ethics',
        'Honesty',
        'Integrity',
        'Maturity',
        'Patience',
        'Presentation',
        'Reliability',
        'Self confidence',
    ],
    organizational: [
        'Categorizing data',
        'Coordinating',
        'Goal setting',
        'Meeting deadlines',
        'Multi-tasking',
        'Prioritizing',
        'Project management',
        'Scheduling',
        'Strategic Planning',
        'Time management',
        'Critical Thinking',
        'Deadline Management',
        'Decisive',
        'Design Strategy',
        'Organizational Skills',
        'Multitasking',
        'Problem-solving',
        'Flexibility',
        'Data Entry',
        'Answering Phones',
        'Billing',
        'MS Office',
        'Office Equipment',
        'QuickBooks',
        'Shipping',
        'Welcoming Visitors',
        'Salesforce',
        'Calendar Management',
    ],
    team: [
        'Collaboration',
        'Communication',
        'Flexibility',
        'Listening',
        'Observation',
        'Participation',
        'Respect',
        'Sharing',
    ],
    personal: [
        'Adaptability',
        'Caring',
        'Common sense',
        'Cooperation',
        'Curiosity',
        'Effort',
        'Flexibility',
        'Friendship',
        'Initiative',
        'Integrity',
        'Organization',
        'Patience',
        'Perseverance',
        'Problem solving',
        'Responsibility',
        'Sense of humor',
        'Stress management',
        'Verbal and nonverbal communication'
    ],
    analytical: [
        'Accountability',
        'Analyzing information',
        'Communication',
        'Critical thinking',
        'Digital literacy',
        'Follow directions',
        'Imagination',
        'Initiative',
        'Organization',
        'Problem solving',
        'Questioning',
        'Reading',
        'Time management',
        'Writing',
        'Analytical skills',
        'Logical thinking',
        'Problem-solving approach',
        'Conceptual abilities',
        'Creative thinking',
        'Deductive reasoning',
        'Inductive reasoning',
        'Critical thinking',
        'Data analysis',
        'Numeracy',
        'Reporting',
        'Research',
        'Troubleshooting',
    ],
    sports: [
        'Concentration',
        'Coordination',
        'Dealing with pressure',
        'Flexibility',
        'Footwork',
        'Performing repetitive drills',
        'Power',
        'Precision',
        'Tactics',
        'Teamwork',
    ],
    business: [
        'Accounting',
        'Administrative',
        'Business intelligence',
        'Clerical',
        'Microsoft office skills',
        'Negotiations',
        'QuickBooks',
        'Business marketing',
        'Customer service',
        'Finance management',
        'Sales',
        'Marketing',
        'Persuasive',
        'Digital marketing',
        'Banking',
        'Insurance',
        'Telecommunications',
        'Business Processes',
        'Product Knowledge',
        'Lead Qualification',
        'Lead Prospecting',
        'Customer Needs Analysis',
        'Referral Marketing',
        'Contract Negotiation',
        'Self Motivation',
        'Increasing Customer Lifetime Value',
        'Reducing Customer Acquisition Cost',
        'CRM Software',
        'POS Skills',
        'Cashier Skills'
    ],
    technical: [
        'Communication Tools',
        'Information Security',
        'Defensive Computing',
        'Data Security',
        'Data Integration',
        'Data Management',
        'Data Mining',
        'Data Analysis',
        'Analytics',
        'Big Data',
        'Cloud Computing',
        'Distrubuted Computing',
        'System Analysis',
        'Architecture',
        'Design',
        'Administration',
        'Infrastructure',
        'Hardware',
        'Troubleshooting',
        'System Integration',
        'Workflow',
        'Consumer Technology',
        'Business Software',
        'Marketing Automation',
        'Ecommerce',
        'Customer Relationship Management',
        'Salesforce Automation',
        'Mobile App Development',
        'User Interface Design',
        'Robotics',
        'Artificial Intelligence',
        'Game Development',
        'Troubleshooting',
        'Networking',
        'Programming Languages',
        'Web Development',
        'Data Structures',
        'Open Source Experience',
        'CodingJava Script',
        'Security',
        'Machine Learning',
        'Debugging',
        'Frontend Development',
        'Back-End Development',
        'Cloud Management',
        'Agile Development',
        'Internet',
        'Operating Systems',
        'Applications',
        'Systems',
        'Platforms',
        'Databases',
        'Software Development',
        'APIs',
        'Scripting',
        'Automation',
        'Networking',
    ],
    communication: [
        'Confidence',
        'Consultation',
        'Customer Service',
        'Establishing Rapport',
        'Interpreting Artwork for the General Public',
        'Understanding Clients’ Artistic Preferences',
        'Interpersonal',
        'Active Listening',
        'Receiving Constructive Criticism about Artwork',
        'Sales',
        'Verbal Communication',
        'Collaboration',
        'Written Communication',
    ],
    creativity: [
        'Aesthetics',
        'Attention to Detail',
        'Balancing Artistry with Audience Appeal',
        'Perceptivity',
        'Visually Representing Ideas',
        'Sketching',
        'Brainstorming',
    ],
    nursing: [
        'Patient Assessment',
        'Taking Vital Signs',
        'Patient Care',
        'Recording Patient Medical History',
        'Wound Dressing and Care',
        'Urgent and Emergency Care',
        'Record-Keeping',
        'Patient Education',
        'NIH Stroke Scale Patient Assessment',
        'Electronic Medical Record',
        'Medicine Administration',
        'Blood Pressure Monitoring',
        'Phlebotomy',
        'Rehabilitation Therapy',
        'Hygiene Assistance',
        'Use of X-Ray", "MRI", "CAT Scans',
        'Meditech',
        'Glucose Checks',
        'Electronic Heart Record',
    ],
}